export const METRIC_INFO = {
  "Fiscal Year": "The company's most recently reported annual fiscal period.",
  Revenue: "Total sales reported for the fiscal year.",
  "Net Income": "Profit remaining after all expenses, taxes, and costs.",
  "Total Assets": "Everything the company owns, per its balance sheet.",
  "Total Liabilities": "Everything the company owes, per its balance sheet.",
  "Stockholders' Equity": "Assets minus liabilities — the company's book value.",
  "Diluted EPS": "Net income per share, assuming all convertible securities are exercised.",
  "52-Week Range": "The lowest and highest closing price over the past year.",
  "Market Cap": "Share price × shares outstanding — the total value of all shares.",
  "Enterprise Value": "Market cap plus total debt, minus cash — the theoretical takeover cost.",
  Cash: "Cash and cash equivalents on the balance sheet.",
  "Total Debt": "Sum of current and non-current long-term debt.",
  Employees: "Employee count as stated in the company's most recent 10-K.",
  Headquarters: "The company's principal executive office location on file with the SEC.",
  Industry: "SEC's SIC (Standard Industrial Classification) code description for this company.",
  EBITDA: "Earnings before interest, taxes, depreciation, and amortization — operating income plus D&A.",
  "P/E Ratio": "Price per share divided by diluted earnings per share.",
  "EV/EBITDA": "Enterprise value divided by EBITDA — a capital-structure-neutral valuation multiple.",
  "EV/Sales": "Enterprise value divided by annual revenue.",
  "Price/Sales": "Market cap divided by annual revenue.",
  "Price/Book": "Market cap divided by stockholders' equity (book value).",
  "Dividend Yield": "Annual dividend per share divided by the current share price.",
  CapEx: "Cash spent acquiring property, plant, and equipment.",
  "R&D": "Research and development expense for the fiscal year.",
  "SG&A": "Selling, general, and administrative expense for the fiscal year.",
  "Stock Buybacks": "Cash spent repurchasing the company's own shares.",
  "Dividends Paid": "Total cash paid out as dividends to shareholders.",
  "Dividend Per Share": "Dividend declared per share of common stock.",
};
